version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "miniforge3-latest"
  jobs:
    post_install:
      - pip install -e . --no-deps -vv

conda:
  environment: environment-dev.yml

sphinx:
  configuration: docs/conf.py
