version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - pip install -e . --no-deps -vv
      - 'python -c "from tams.data import download_examples; download_examples()"'

conda:
  environment: environment-dev.yml

sphinx:
  configuration: docs/conf.py
