version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - pip install -e . --no-deps -vv
      - 'python -c "from tams.data import download_examples; download_examples()"'

conda:
  environment: environment-dev.yml
