name: tams-dev
channels:
  - conda-forge
dependencies:
  - python =3.11
  - pip
  #
  # Core dependencies
  - geopandas >=0.10
  - matplotlib >=3.4,!=3.8.0
  - numpy
  - pandas =2.*
  - scikit-image
  - shapely
  - xarray
  #
  # Extras
  - cartopy >=0.21
  - dask-core
  - earthaccess
  - gdown
  - h5netcdf
  - joblib
  - netcdf4
  - regionmask >=0.9
  - scipy
  - seaborn >=0.13.2
  #
  # Development and tests
  - flit
  - ipywidgets
  - jupyterlab
  - mypy
  - pytest >=6.0
  - pytest-mock
  - rich
  #
  # Docs
  - docutils
  - myst-nb
  - myst-parser
  - sphinx =8.*
  - sphinx-autobuild
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-togglebutton
  - sphinxcontrib-bibtex
  - watermark
  - pip:
      - sphinx-prompt
      - sphinxext-opengraph
      - xrframes >=0.0.4
