name: tams-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  #
  # Core dependencies
  - geopandas>=0.10
  - matplotlib>=3.4
  - numpy
  - pandas
  - scikit-image
  - shapely
  - xarray
  #
  # Extras
  - cartopy>=0.21
  - joblib
  - netcdf4
  - ptitprince
  - pygeos
  - regionmask
  - scipy
  #
  # Development and tests
  - flit
  - jupyterlab
  - mypy
  - pytest>=6.0
  #
  # Docs
  - myst-nb
  - myst-parser
  - sphinx=4.*
  - sphinx-autobuild
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinxcontrib-bibtex
  - pip:
      - sphinx-prompt
      - sphinxext-opengraph
