name: tams-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  #
  # Core dependencies
  - cartopy
  - geopandas>=0.10
  - matplotlib>=3.4
  - netcdf4
  - numpy
  - pygeos
  - pyproj
  - regionmask
  - scikit-image
  - scipy
  - shapely
  - xarray
  #
  # Extras
  - joblib
  - ptitprince
  #
  # Development and tests
  - jupyterlab
  - mypy
  - pytest
  #
  # Docs
  - myst-nb
  - myst-parser
  - sphinx>=4.0
  - sphinx-autobuild
  - sphinx-book-theme
