name: tams-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  #
  - cartopy
  - geopandas>=0.10
  - matplotlib>=3.4
  - netcdf4
  - numpy
  - pygeos
  - pyproj
  - regionmask
  - scikit-image
  - scipy
  - shapely
  - xarray
  #
  - jupyterlab
  - mypy
  - pytest
