name: tams-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  #
  - geopandas
  - matplotlib>=3.4
  - netcdf4
  - numpy
  - regionmask
  - scikit-image
  - scipy
  - xarray
  #
  - jupyterlab
