name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 12 1,15 * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-dev.yml
          cache-environment: true

      - name: pytest
        run: pytest -v -ra test_tams.py

      - name: Run as script
        run: python -m tams.core

      - name: mypy
        run: |
          mypy --install-types --non-interactive \
            --ignore-missing-imports \
            tams test_tams.py
