name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          cache-environment: true

      - name: Download the sample data
        run: python -c "from tams.data import download_examples; download_examples()"

      - name: pytest
        run: pytest test_tams.py

      - name: Run as script
        run: python -m tams.core

      - name: mypy
        run: |
          mypy --install-types --non-interactive \
            --ignore-missing-imports \
            tams test_tams.py
